openapi: 3.0.0
info:
  title: "Peanotes Flask API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
    Note:
      type: "object"
      properties:
        person_id:
          type: "integer"
        content:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "Last name of the person to get"
      in: path
      required: True
      schema:
        type: "string"
    note_id:
      name: "note_id"
      description: "ID of the note"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "people.create"
      tags:
        - "People"
      summary: "Create a person"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        "201":
          description: "Successfully created a person"
  /people/{lname}:
    get:
      operationId: "people.read_one"
      tags:
        - "People"
      summary: "Read one person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Successfully read person"
    put:
      operationId: "people.update"
      tags:
        - "People"
      summary: "Update a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
      responses:
        "200":
          description: "Successfully updated person"
    delete:
      operationId: "people.delete"
      tags:
        - "People"
      summary: "Delete a person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Successfylly deleted person"
  /notes:
    post:
      operationId: "notes.create"
      tags: 
        - "Notes"
      summary: "Create a note associated with a person"
      requestBody:
        description: "Note to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "note"
              $ref: "#/components/schemas/Note"
      responses:
        "201":
          description: "Successfully created a note"
  /notes/{note_id}:
    get:
      operationId: "notes.read_one"
      tags:
        - "Notes"
      summary: "Read one note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "200":
          description: "Successfully read one note"
    put:
      operationId: "notes.update"
      tags:
        - "Notes"
      summary: "Update a note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "note"
              type: "object"
              properties:
                content:
                  type: "string"
      responses:
        "200":
          description: "Successfully updated note"
    delete:
      operationId: "notes.delete"
      tags:
        - "Notes"
      summary: "Delete a note"
      parameters:
        - $ref: "#/components/parameters/note_id"
      responses:
        "204":
          description: "Successfully deleted note"